# Generated by Django 3.2 on 2021-04-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0004_auto_20210406_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
