# Generated by Django 3.2 on 2021-04-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0007_remove_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
