# Generated by Django 3.2 on 2021-04-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0008_user_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedSurveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('survey', models.CharField(max_length=100)),
                ('questions', models.CharField(default='.', max_length=200)),
                ('answers', models.CharField(default='.', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='people',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyapp.survey')),
            ],
        ),
    ]
