# Generated by Django 3.2 on 2021-04-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0010_alter_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='users',
            field=models.CharField(default='', max_length=500),
        ),
    ]
