# Generated by Django 3.1.6 on 2021-04-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0012_auto_20210415_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedsurveys',
            old_name='answers',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='submittedsurveys',
            old_name='questions',
            new_name='question',
        ),
    ]
