# Generated by Django 3.1.6 on 2021-04-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0013_auto_20210415_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='choice1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='choice2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='choice3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='choice4',
            field=models.IntegerField(default=0),
        ),
    ]
